parameters:
    doctrine.intl.translatable_subscriber.class: Doctrine\Intl\Model\ORM\TranslatableSubscriber
    doctrine.intl.translatable_subscriber.translatable_fetch_method: LAZY
    doctrine.intl.translatable_subscriber.translation_fetch_method: LAZY

services:
    doctrine.intl.translatable_subscriber:
        class:   "%doctrine.intl.translatable_subscriber.class%"
        public:  false
        arguments:
            - "%doctrine.intl.translatable_subscriber.translatable_fetch_method%"
            - "%doctrine.intl.translatable_subscriber.translation_fetch_method%"
        tags:
            - { name: doctrine.event_subscriber }