parameters:
    doctrine.intl.translatable_subscriber.class: Doctrine\Intl\Model\ORM\TranslatableSubscriber
    #doctrine.intl.translatable_subscriber.current_locale_callable.class: Doctrine\Intl\ORM\Translatable\CurrentLocaleCallable
    #doctrine.intl.translatable_subscriber.translatable_trait: Doctrine\Intl\Model\Translatable\Translatable
    #doctrine.intl.translatable_subscriber.translation_trait: Doctrine\Intl\Model\Translatable\Translation
    #doctrine.intl.translatable_subscriber.translatable_fetch_method: LAZY
    #doctrine.intl.translatable_subscriber.translation_fetch_method: LAZY

services:
    #doctrine.intl.reflection.class_analyzer:
    #    class:   "%doctrine.intl.reflection.class_analyzer.class%"
    #    public:  false

    doctrine.intl.translatable_subscriber:
        class:   "%doctrine.intl.translatable_subscriber.class%"
        public:  false
        #arguments:
        #    - "@doctrine.intl.reflection.class_analyzer"
        #    - "%doctrine.intl.reflection.is_recursive%"
        #    - "@doctrine.intl.translatable_subscriber.current_locale_callable"
        #    - "%doctrine.intl.translatable_subscriber.translatable_trait%"
        #    - "%doctrine.intl.translatable_subscriber.translation_trait%"
        #    - "%doctrine.intl.translatable_subscriber.translatable_fetch_method%"
        #    - "%doctrine.intl.translatable_subscriber.translation_fetch_method%"
        tags:
            - { name: doctrine.event_subscriber }

    #doctrine.intl.translatable_subscriber.current_locale_callable:
    #    class: "%doctrine.intl.translatable_subscriber.current_locale_callable.class%"
    #    arguments:
    #        - "@service_container" # lazy request resolution
    #    public:  false