parameters:
    knp.doctrine_behaviors.translatable_subscriber.class: Knp\DoctrineBehaviors\ORM\Translatable\TranslatableSubscriber
    knp.doctrine_behaviors.translatable_subscriber.current_locale_callable.class: Knp\DoctrineBehaviors\ORM\Translatable\CurrentLocaleCallable
    knp.doctrine_behaviors.translatable_subscriber.translatable_trait: Knp\DoctrineBehaviors\Model\Translatable\Translatable
    knp.doctrine_behaviors.translatable_subscriber.translation_trait: Knp\DoctrineBehaviors\Model\Translatable\Translation
    knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method: LAZY
    knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method: LAZY

services:
    knp.doctrine_behaviors.reflection.class_analyzer:
        class:   "%knp.doctrine_behaviors.reflection.class_analyzer.class%"
        public:  false

    knp.doctrine_behaviors.translatable_subscriber:
        class:   "%knp.doctrine_behaviors.translatable_subscriber.class%"
        public:  false
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "@knp.doctrine_behaviors.translatable_subscriber.current_locale_callable"
            - "%knp.doctrine_behaviors.translatable_subscriber.translatable_trait%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translation_trait%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method%"
        tags:
            - { name: doctrine.event_subscriber }

    knp.doctrine_behaviors.translatable_subscriber.current_locale_callable:
        class: "%knp.doctrine_behaviors.translatable_subscriber.current_locale_callable.class%"
        arguments:
            - "@service_container" # lazy request resolution
        public:  false